const mongoose = require('mongoose');
const VehicleDatabase = require('../models/vehicleDatabase');
require('dotenv').config();

// Connect to MongoDB
const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/taxtron');
    console.log('MongoDB connected');
  } catch (error) {
    console.error('MongoDB connection error:', error);
    process.exit(1);
  }
};

// Dummy vehicle data
const dummyVehicles = [
  {
    chassisNumber: 'JHMFA1F80AS123456',
    make: 'Honda',
    model: 'Civic',
    variant: '1.8L EX',
    year: 2023,
    engineNumber: 'R18A1-123456',
    engineCapacity: 1799,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    color: 'White',
    bodyType: 'Sedan',
    seatingCapacity: 5,
    length: 4640,
    width: 1800,
    height: 1415,
    wheelbase: 2700,
    power: 140,
    torque: 174,
    topSpeed: 200,
    acceleration: 9.2,
    safetyFeatures: ['ABS', 'Airbags', 'EBD', 'ESP', 'Parking Sensors'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Honda Motor Company',
    vehicleCategory: 'Passenger Vehicle',
    basePrice: 4500000,
    taxRate: 15
  },
  {
    chassisNumber: 'WBAFR7C50BC123789',
    make: 'BMW',
    model: '3 Series',
    variant: '320i Luxury',
    year: 2023,
    engineNumber: 'B48B20-789123',
    engineCapacity: 1998,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    color: 'Black',
    bodyType: 'Sedan',
    seatingCapacity: 5,
    length: 4709,
    width: 1827,
    height: 1442,
    wheelbase: 2851,
    power: 184,
    torque: 300,
    topSpeed: 235,
    acceleration: 7.1,
    safetyFeatures: ['ABS', 'Airbags', 'EBD', 'ESP', 'TCS', 'Hill Assist', 'Parking Sensors', 'Reverse Camera'],
    countryOfOrigin: 'Germany',
    manufacturer: 'BMW Group',
    vehicleCategory: 'Passenger Vehicle',
    basePrice: 8500000,
    taxRate: 20
  },
  {
    chassisNumber: '1HGBH41JXMN109186',
    make: 'Toyota',
    model: 'Corolla',
    variant: '1.6L XLI',
    year: 2023,
    engineNumber: '2ZR-FE-109186',
    engineCapacity: 1598,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'Silver',
    bodyType: 'Sedan',
    seatingCapacity: 5,
    length: 4635,
    width: 1780,
    height: 1435,
    wheelbase: 2700,
    power: 132,
    torque: 160,
    topSpeed: 190,
    acceleration: 10.4,
    safetyFeatures: ['ABS', 'Airbags', 'EBD', 'ESP'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Toyota Motor Corporation',
    vehicleCategory: 'Passenger Vehicle',
    basePrice: 3800000,
    taxRate: 15
  },
  {
    chassisNumber: 'KMHDN45D5NU123456',
    make: 'Hyundai',
    model: 'Elantra',
    variant: '2.0L GLS',
    year: 2023,
    engineNumber: 'Nu-123456',
    engineCapacity: 1999,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    color: 'Red',
    bodyType: 'Sedan',
    seatingCapacity: 5,
    length: 4620,
    width: 1800,
    height: 1450,
    wheelbase: 2700,
    power: 152,
    torque: 192,
    topSpeed: 200,
    acceleration: 9.8,
    safetyFeatures: ['ABS', 'Airbags', 'EBD', 'ESP', 'Parking Sensors'],
    countryOfOrigin: 'South Korea',
    manufacturer: 'Hyundai Motor Company',
    vehicleCategory: 'Passenger Vehicle',
    basePrice: 4200000,
    taxRate: 15
  },
  {
    chassisNumber: 'WDB2060011A123456',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    variant: 'C200 Avantgarde',
    year: 2023,
    engineNumber: 'M274-123456',
    engineCapacity: 1991,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    color: 'Blue',
    bodyType: 'Sedan',
    seatingCapacity: 5,
    length: 4686,
    width: 1810,
    height: 1442,
    wheelbase: 2840,
    power: 184,
    torque: 300,
    topSpeed: 240,
    acceleration: 7.3,
    safetyFeatures: ['ABS', 'Airbags', 'EBD', 'ESP', 'TCS', 'Hill Assist', 'Parking Sensors', 'Reverse Camera', 'Lane Assist'],
    countryOfOrigin: 'Germany',
    manufacturer: 'Mercedes-Benz AG',
    vehicleCategory: 'Passenger Vehicle',
    basePrice: 12000000,
    taxRate: 25
  },
  {
    chassisNumber: 'JT2BF28K123456789',
    make: 'Toyota',
    model: 'Hilux',
    variant: '2.4L 4WD',
    year: 2023,
    engineNumber: '2GD-FTV-123456',
    engineCapacity: 2393,
    fuelType: 'Diesel',
    transmission: 'Manual',
    color: 'White',
    bodyType: 'Pickup',
    seatingCapacity: 5,
    length: 5335,
    width: 1855,
    height: 1815,
    wheelbase: 3085,
    power: 150,
    torque: 400,
    topSpeed: 180,
    acceleration: 12.5,
    safetyFeatures: ['ABS', 'Airbags', 'EBD', 'ESP', 'Hill Assist'],
    countryOfOrigin: 'Thailand',
    manufacturer: 'Toyota Motor Corporation',
    vehicleCategory: 'Commercial Vehicle',
    basePrice: 5500000,
    taxRate: 18
  },
  {
    chassisNumber: 'MAJ3A1F80AS987654',
    make: 'Suzuki',
    model: 'Swift',
    variant: '1.2L VDI',
    year: 2023,
    engineNumber: 'K12M-987654',
    engineCapacity: 1197,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'Orange',
    bodyType: 'Hatchback',
    seatingCapacity: 5,
    length: 3840,
    width: 1695,
    height: 1530,
    wheelbase: 2450,
    power: 82,
    torque: 113,
    topSpeed: 170,
    acceleration: 11.8,
    safetyFeatures: ['ABS', 'Airbags', 'EBD'],
    countryOfOrigin: 'India',
    manufacturer: 'Maruti Suzuki',
    vehicleCategory: 'Passenger Vehicle',
    basePrice: 2500000,
    taxRate: 12
  },
  {
    chassisNumber: 'KMHTC6ADXNU654321',
    make: 'Hyundai',
    model: 'Tucson',
    variant: '2.0L GLS 4WD',
    year: 2023,
    engineNumber: 'Theta-II-654321',
    engineCapacity: 1999,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    color: 'Black',
    bodyType: 'SUV',
    seatingCapacity: 5,
    length: 4480,
    width: 1850,
    height: 1660,
    wheelbase: 2670,
    power: 155,
    torque: 192,
    topSpeed: 200,
    acceleration: 9.5,
    safetyFeatures: ['ABS', 'Airbags', 'EBD', 'ESP', 'TCS', 'Hill Assist', 'Parking Sensors', 'Reverse Camera'],
    countryOfOrigin: 'South Korea',
    manufacturer: 'Hyundai Motor Company',
    vehicleCategory: 'Passenger Vehicle',
    basePrice: 6500000,
    taxRate: 18
  },

  // MOTORCYCLES
  {
    chassisNumber: 'YAMAHA123456789YZF',
    make: 'Yamaha',
    model: 'YZF-R15',
    variant: 'V4',
    year: 2023,
    engineNumber: '155LC-123456',
    engineCapacity: 155,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'Blue',
    bodyType: 'Motorcycle',
    seatingCapacity: 2,
    length: 1990,
    width: 725,
    height: 1135,
    wheelbase: 1325,
    power: 18.6,
    torque: 14.1,
    topSpeed: 136,
    acceleration: 12.4,
    safetyFeatures: ['ABS', 'Other'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Yamaha Motor Company',
    vehicleCategory: 'Two Wheeler',
    basePrice: 450000,
    taxRate: 8
  },
  {
    chassisNumber: 'HONDA150CC789ABC',
    make: 'Honda',
    model: 'CB150F',
    variant: 'Standard',
    year: 2023,
    engineNumber: 'CB150-789123',
    engineCapacity: 149,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'Red',
    bodyType: 'Motorcycle',
    seatingCapacity: 2,
    length: 2017,
    width: 780,
    height: 1067,
    wheelbase: 1290,
    power: 12.73,
    torque: 12.8,
    topSpeed: 120,
    acceleration: 15.2,
    safetyFeatures: ['Other'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Honda Motor Company',
    vehicleCategory: 'Two Wheeler',
    basePrice: 280000,
    taxRate: 8
  },
  {
    chassisNumber: 'SUZUKI70CC456DEF',
    make: 'Suzuki',
    model: 'GS150',
    variant: 'SE',
    year: 2023,
    engineNumber: 'GS150-456789',
    engineCapacity: 148,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'Black',
    bodyType: 'Motorcycle',
    seatingCapacity: 2,
    length: 2000,
    width: 760,
    height: 1050,
    wheelbase: 1280,
    power: 13.8,
    torque: 12.2,
    topSpeed: 115,
    acceleration: 14.8,
    safetyFeatures: ['Other'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Suzuki Motor Corporation',
    vehicleCategory: 'Two Wheeler',
    basePrice: 260000,
    taxRate: 8
  },

  // BUSES
  {
    chassisNumber: 'DAEWOOBUS123456789',
    make: 'Daewoo',
    model: 'DB101',
    variant: 'Luxury Coach',
    year: 2022,
    engineNumber: 'DL08-123456',
    engineCapacity: 8000,
    fuelType: 'Diesel',
    transmission: 'Manual',
    color: 'White',
    bodyType: 'Bus',
    seatingCapacity: 45,
    length: 12000,
    width: 2500,
    height: 3200,
    wheelbase: 6000,
    power: 300,
    torque: 1200,
    topSpeed: 120,
    acceleration: 25.0,
    safetyFeatures: ['ABS', 'Other'],
    countryOfOrigin: 'South Korea',
    manufacturer: 'Daewoo Bus Corporation',
    vehicleCategory: 'Heavy Vehicle',
    basePrice: 8500000,
    taxRate: 18
  },
  {
    chassisNumber: 'HINO500BUS789123',
    make: 'Hino',
    model: 'RK1JSKA',
    variant: 'City Bus',
    year: 2023,
    engineNumber: 'J08E-456789',
    engineCapacity: 7684,
    fuelType: 'Diesel',
    transmission: 'Manual',
    color: 'Blue',
    bodyType: 'Bus',
    seatingCapacity: 35,
    length: 10500,
    width: 2490,
    height: 3050,
    wheelbase: 5200,
    power: 240,
    torque: 981,
    topSpeed: 100,
    acceleration: 22.0,
    safetyFeatures: ['ABS', 'Other'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Hino Motors',
    vehicleCategory: 'Heavy Vehicle',
    basePrice: 7200000,
    taxRate: 18
  },

  // TRUCKS
  {
    chassisNumber: 'ISUZU123TRUCK456',
    make: 'Isuzu',
    model: 'NPR',
    variant: '4HK1 Turbo',
    year: 2023,
    engineNumber: '4HK1-123456',
    engineCapacity: 5193,
    fuelType: 'Diesel',
    transmission: 'Manual',
    color: 'White',
    bodyType: 'Truck',
    seatingCapacity: 3,
    length: 6995,
    width: 2195,
    height: 2285,
    wheelbase: 3815,
    power: 190,
    torque: 510,
    topSpeed: 120,
    acceleration: 18.5,
    safetyFeatures: ['ABS', 'Reverse Camera'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Isuzu Motors',
    vehicleCategory: 'Commercial Vehicle',
    basePrice: 4500000,
    taxRate: 15
  },
  {
    chassisNumber: 'MITSUBISHI789CANT',
    make: 'Mitsubishi',
    model: 'Canter',
    variant: '3.0L 4D34',
    year: 2022,
    engineNumber: '4D34-789123',
    engineCapacity: 2977,
    fuelType: 'Diesel',
    transmission: 'Manual',
    color: 'Yellow',
    bodyType: 'Truck',
    seatingCapacity: 3,
    length: 5995,
    width: 1890,
    height: 2050,
    wheelbase: 3200,
    power: 130,
    torque: 304,
    topSpeed: 110,
    acceleration: 16.2,
    safetyFeatures: ['ABS', 'Other'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Mitsubishi Fuso',
    vehicleCategory: 'Commercial Vehicle',
    basePrice: 3200000,
    taxRate: 15
  },

  // VANS
  {
    chassisNumber: 'SUZUKIAPV123456789',
    make: 'Suzuki',
    model: 'APV',
    variant: 'GLX',
    year: 2023,
    engineNumber: 'G10A-123456',
    engineCapacity: 1061,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'Silver',
    bodyType: 'Van',
    seatingCapacity: 8,
    length: 4190,
    width: 1680,
    height: 1895,
    wheelbase: 2500,
    power: 65,
    torque: 84,
    topSpeed: 140,
    acceleration: 14.8,
    safetyFeatures: ['Other'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Suzuki Motor Corporation',
    vehicleCategory: 'Commercial Vehicle',
    basePrice: 1800000,
    taxRate: 12
  },
  {
    chassisNumber: 'TOYOTA456HIACE789',
    make: 'Toyota',
    model: 'HiAce',
    variant: '2.7L GL',
    year: 2023,
    engineNumber: '2TR-456789',
    engineCapacity: 2694,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'White',
    bodyType: 'Van',
    seatingCapacity: 15,
    length: 5380,
    width: 1880,
    height: 2285,
    wheelbase: 3210,
    power: 163,
    torque: 245,
    topSpeed: 160,
    acceleration: 12.5,
    safetyFeatures: ['ABS', 'Airbags'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Toyota Motor Corporation',
    vehicleCategory: 'Commercial Vehicle',
    basePrice: 4200000,
    taxRate: 15
  },

  // RICKSHAWS/AUTO-RICKSHAWS
  {
    chassisNumber: 'QINGQI200CC123456',
    make: 'Qingqi',
    model: 'QM200ZH-3C',
    variant: 'Auto Rickshaw',
    year: 2023,
    engineNumber: 'QM200-123456',
    engineCapacity: 200,
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'Green',
    bodyType: 'Other',
    seatingCapacity: 3,
    length: 2800,
    width: 1400,
    height: 1750,
    wheelbase: 1950,
    power: 13,
    torque: 15,
    topSpeed: 60,
    acceleration: 18.0,
    safetyFeatures: ['Other'],
    countryOfOrigin: 'China',
    manufacturer: 'Qingqi Motorcycle',
    vehicleCategory: 'Three Wheeler',
    basePrice: 350000,
    taxRate: 10
  },

  // HEAVY TRUCKS
  {
    chassisNumber: 'HINO700HEAVY12345',
    make: 'Hino',
    model: '700 Series',
    variant: 'SS2PKIA Heavy Duty',
    year: 2022,
    engineNumber: 'A09C-123456',
    engineCapacity: 8866,
    fuelType: 'Diesel',
    transmission: 'Manual',
    color: 'Blue',
    bodyType: 'Truck',
    seatingCapacity: 2,
    length: 8500,
    width: 2490,
    height: 3200,
    wheelbase: 4600,
    power: 350,
    torque: 1422,
    topSpeed: 90,
    acceleration: 28.0,
    safetyFeatures: ['ABS', 'Other'],
    countryOfOrigin: 'Japan',
    manufacturer: 'Hino Motors',
    vehicleCategory: 'Heavy Vehicle',
    basePrice: 12000000,
    taxRate: 20
  }
];

// Function to populate database
const populateDatabase = async () => {
  try {
    // Clear existing data
    await VehicleDatabase.deleteMany({});
    console.log('Cleared existing vehicle data');
    
    // Insert dummy data
    await VehicleDatabase.insertMany(dummyVehicles);
    console.log(`Successfully added ${dummyVehicles.length} vehicles to database`);
    
    // Display summary
    const totalVehicles = await VehicleDatabase.countDocuments();
    console.log(`Total vehicles in database: ${totalVehicles}`);
    
    // Display makes
    const makes = await VehicleDatabase.distinct('make');
    console.log('Available makes:', makes.join(', '));
    
  } catch (error) {
    console.error('Error populating database:', error);
  } finally {
    mongoose.connection.close();
    console.log('Database connection closed');
  }
};

// Run the script
connectDB().then(() => {
  populateDatabase();
});

module.exports = { dummyVehicles };
